---
common_packages:
  # neovim requirements
  - make
  - gcc
  - ripgrep
  - zip
  - unzip
  # most importants
  - neovim
  - tmux
  - alacritty
  # QOL
  - fzf
  - zoxide
  - fastfetch
  - stow
  - mpv
  - lsd
  - ncdu
  - procs
  - bat
  - duf
  - tealdeer
  - btop
  - git-delta
  # additions
  - trash-cli
  - bash-completion
  - file
  - ufw
  - flatpak
  - npm
  - rsync
  - qutebrowser
  - jq

specific_packages:
  Debian:
    - xclip
    - vim
    - starship
    - sd
    - du-dust
    - ranger
    - fd-find
    - ffmpeg
    - keyd
    - libreoffice
    - python3
    - gh

  Archlinux:
    - vim
    - starship
    - sd
    - dust
    - yazi
    - fd
    - ffmpeg
    - keyd
    - libreoffice-still
    - python
    - uv
    - github-cli
    - obsidian
    - ncspot
    - ueberzugpp
    - openssh
    - zathura
    - zathura-pdf-poppler

  RedHat:
    - vim-enhanced
    - sd
    - du-dust
    - ranger
    - fd-find
    - ffmpeg-free
    - libreoffice
    - python3
    - uv
    - gh
    # no keyd regularly on fedora, google how to dl
    # no starship on fedora dnf??
